---
config:
  enabled: true
  configMap:
    FRONTEND_KC_CLIENTID: ches-showcase-frontend-4105
    FRONTEND_KC_REALM: standard
    FRONTEND_KC_SERVERURL: https://test.loginproxy.gov.bc.ca/auth
    # FRONTEND_DASHBOARDURL: https://ches-metabase.apps.silver.devops.gov.bc.ca/public/dashboard/6f388f95-dba7-4632-be4c-8855ee645f31
    SERVER_KC_PUBLICKEY: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAiFdv9GA83uHuy8Eu9yiZHGGF9j6J8t7FkbcpaN81GDjwbjsIJ0OJO9dKRAx6BAtTC4ubJTBJMPvQER5ikOhIeBi4o25fg61jpgsU6oRZHkCXc9gX6mrjMjbsPaf3/bjjYxP5jicBDJQeD1oRa24+tiGggoQ7k6gDEN+cRYqqNpzC/GQbkUPk8YsgroncEgu8ChMh/3ERsLV2zorchMANUq76max16mHrhtWIQxrb/STpSt4JuSlUzzBV/dcXjJe5gywZHe0jAutFhNqjHzHdgyaC4RAd3eYQo+Kl/JOgy2AZrnx+CiPmvOJKe9tAW4k4H087ng8aVE40v4HW/FEbnwIDAQAB
    SERVER_KC_REALM: standard
    SERVER_KC_SERVERURL: https://test.loginproxy.gov.bc.ca/auth
    # SERVER_LOGFILE: ./app.log
    SERVER_LOGLEVEL: http
    SERVER_PORT: "8080"
    SC_CHES_ENDPOINT: https://ches-test.api.gov.bc.ca/api
    SC_CS_TOKEN_ENDPOINT: https://test.loginproxy.gov.bc.ca/auth/realms/comsvcauth/protocol/openid-connect/token
